Repository Schoelxz/DayAtStunlock, pull requests merged in 2018-06, with the labels that each got.

#93 Feature/add credits screen
  ADayAtStunlock/Assets/Prefabs/UI/MainMenuCanvas.prefab
  ADayAtStunlock/Assets/Scenes/MainMenu.unity
Labels: enhancement

#94 Feature/tooltip fix
  ADayAtStunlock/Assets/Prefabs/UI/ConfigCanvas.prefab
  ADayAtStunlock/Assets/Prefabs/UI/GameHUDCanvas.prefab
  ADayAtStunlock/Assets/Prefabs/UI/IngameMenu.prefab
  ADayAtStunlock/Assets/Prefabs/UI/Tooltip.prefab
  ADayAtStunlock/Assets/Prefabs/UI/Tooltip.prefab.meta
  ADayAtStunlock/Assets/Scenes/GameScene.unity
  ADayAtStunlock/Assets/Scenes/MainMenu.unity
  ADayAtStunlock/Assets/Scripts/Audio/UpdateSliderValue.cs
  ADayAtStunlock/Assets/Scripts/UI-Related/TooltipMover.cs
Labels: enhancement

#95 Warning lights
  ADayAtStunlock/Assets/Prefabs/Events/TrainEventPrefab.prefab
  ADayAtStunlock/Assets/Scenes/GameScene.unity
  ADayAtStunlock/Assets/Scripts/Random Events/BlinkingLight.cs
  ADayAtStunlock/Assets/Scripts/Random Events/BlinkingLight.cs.meta
Labels: enhancement

#96 Feature/fixing broken things
  ADayAtStunlock/Assets/Prefabs/UI/ConfigCanvas.prefab
  ADayAtStunlock/Assets/Prefabs/UI/CreditsCanvas.prefab
  ADayAtStunlock/Assets/Prefabs/UI/CreditsCanvas.prefab.meta
  ADayAtStunlock/Assets/Prefabs/UI/GameHUDCanvas.prefab
  ADayAtStunlock/Assets/Prefabs/UI/IngameMenu.prefab
  ADayAtStunlock/Assets/Prefabs/UI/Tooltip.prefab
  ADayAtStunlock/Assets/Scenes/GameScene.unity
  ADayAtStunlock/Assets/Scenes/MainMenu.unity
  ADayAtStunlock/Assets/Scripts/UI-Related/TooltipMover.cs
Labels: enhancement

#97 Now makes sure the game is paused when a relevant menu is open.
  ADayAtStunlock/Assets/Scenes/MainMenu.unity
  ADayAtStunlock/Assets/Scripts/Time/PauseGame.cs
  ADayAtStunlock/Assets/Scripts/Time/PauseGame.cs.meta
Labels: bug, enhancement

#98 Fixed bug with newly added puasegame script which made speedup not work.
  ADayAtStunlock/Assets/Scenes/MainMenu.unity
  ADayAtStunlock/Assets/Scripts/Time/PauseGame.cs
Labels: bug

#99 Now stops all non-music sound effects after you lose the game.
  ADayAtStunlock/Assets/Scripts/Audio/AudioManager.cs
  ADayAtStunlock/Assets/Scripts/Npc/MoneyManager.cs
Labels: bug, enhancement

#100 Fixed some variables to make the arrows not overlap with the UI
  ADayAtStunlock/Assets/Scenes/GameScene.unity
  ADayAtStunlock/Assets/Scripts/Npc/UI/FindNpcInUI.cs
  ADayAtStunlock/Assets/Scripts/UI-Related/ArrowPointer.cs
Labels: bug, enhancement

#101 Feature/tutorial splash
  ADayAtStunlock/Assets/Graphics/Materials/Furniture/RadiatorMat.mat
  ADayAtStunlock/Assets/Graphics/Materials/Infrastructure/Decoration/WallTextMat.mat
  ADayAtStunlock/Assets/Graphics/Textures/UI/Icons/NPC_PointerArrow_02.png
  ADayAtStunlock/Assets/Graphics/Textures/UI/Icons/NPC_PointerArrow_02.png.meta
  ADayAtStunlock/Assets/Graphics/Textures/UI/Logo/StudioLogo.png
  ADayAtStunlock/Assets/Graphics/Textures/UI/Logo/StudioLogo.png.meta
  ADayAtStunlock/Assets/Graphics/Textures/UI/tutorial_stuff/workstation_New.JPG
  ADayAtStunlock/Assets/Graphics/Textures/UI/tutorial_stuff/workstation_New.JPG.meta
  ADayAtStunlock/Assets/Graphics/Textures/UI/tutorial_stuff/workstation_loss.JPG
  ADayAtStunlock/Assets/Graphics/Textures/UI/tutorial_stuff/workstation_loss.JPG.meta
  ADayAtStunlock/Assets/Prefabs/UI/totorial_canvas.prefab
Labels: enhancement
